---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
  when: ansible_facts['distribution'] == 'Ubuntu'
- name: Include version-specific variables for Debian
  ansible.builtin.include_vars: "Debian-{{ ansible_facts['distribution_major_version'] }}.yml"
  when: ansible_facts['distribution'] == 'Debian'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_facts['distribution_major_version'] }}.yml"
  when: ansible_facts['os_family'] == "RedHat"

- name: Import faup
  ansible.builtin.import_tasks: faup.yml
